services:
  nginx:
    image: nginx:latest
    container_name: nginx-server
    restart: always
    networks:
      - dbnet
    expose:
      - 8088
    ports:
      - "80:8088"
    volumes:
      - ./sitewomen/static:/app/www/sitewomen/static
      - ./sitewomen/media:/app/www/sitewomen/media
      - ./sitewomen/logs:/app/www/sitewomen/logs
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - sitewomen

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - dbnet
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  sitewomen:
    build:
      context: ./sitewomen
    image: sitewomen
    container_name: sitewomen
    restart: always
#    command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn -c gunicorn.py sitewomen.wsgi
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
    links:
      - "postgres:dbps"
    networks:
      - dbnet
    volumes:
      - ./sitewomen:/app/www/sitewomen
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8080:8080"
    links:
      - "postgres:db"
    networks:
      - dbnet
    depends_on:
      - postgres

  postgres:
    image: postgres:17-alpine
    container_name: psgr
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - dbnet

networks:
  dbnet:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local